#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : python-dotenv
Version  : 0.19.1
Release  : 14
URL      : https://files.pythonhosted.org/packages/36/b7/08860463445e6f3b4c5ac24717ce0e8a2f6e9dbc329b0e5d148094ce89ec/python-dotenv-0.19.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/36/b7/08860463445e6f3b4c5ac24717ce0e8a2f6e9dbc329b0e5d148094ce89ec/python-dotenv-0.19.1.tar.gz
Summary  : Read key-value pairs from a .env file and set them as environment variables
Group    : Development/Tools
License  : BSD-3-Clause
Requires: python-dotenv-bin = %{version}-%{release}
Requires: python-dotenv-license = %{version}-%{release}
Requires: python-dotenv-python = %{version}-%{release}
Requires: python-dotenv-python3 = %{version}-%{release}
Requires: click
Requires: flake8
Requires: ipython
Requires: python-mock
Requires: tox
Requires: twine
Requires: wheel
BuildRequires : buildreq-distutils3
BuildRequires : click
BuildRequires : flake8
BuildRequires : ipython
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : python-mock
BuildRequires : tox
BuildRequires : twine
BuildRequires : virtualenv
BuildRequires : wheel

%description
# python-dotenv
[![Build Status][build_status_badge]][build_status_link]
[![PyPI version][pypi_badge]][pypi_link]

%package bin
Summary: bin components for the python-dotenv package.
Group: Binaries
Requires: python-dotenv-license = %{version}-%{release}

%description bin
bin components for the python-dotenv package.


%package license
Summary: license components for the python-dotenv package.
Group: Default

%description license
license components for the python-dotenv package.


%package python
Summary: python components for the python-dotenv package.
Group: Default
Requires: python-dotenv-python3 = %{version}-%{release}

%description python
python components for the python-dotenv package.


%package python3
Summary: python3 components for the python-dotenv package.
Group: Default
Requires: python3-core
Provides: pypi(python_dotenv)

%description python3
python3 components for the python-dotenv package.


%prep
%setup -q -n python-dotenv-0.19.1
cd %{_builddir}/python-dotenv-0.19.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1634158134
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/python-dotenv
cp %{_builddir}/python-dotenv-0.19.1/LICENSE %{buildroot}/usr/share/package-licenses/python-dotenv/36fe354f4526001c781c4c99847c059ebc00878c
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/dotenv

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/python-dotenv/36fe354f4526001c781c4c99847c059ebc00878c

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
